-- Sistema de Gestion de Usuarios y Roles
-- Oracle Autonomous Database

DROP TABLE USUARIO_ROL CASCADE CONSTRAINTS;
DROP TABLE TOKEN_RECUPERACION CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE ROLES CASCADE CONSTRAINTS;

CREATE TABLE USUARIOS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE          VARCHAR2(80)  NOT NULL,
    APELLIDO        VARCHAR2(80)  NOT NULL,
    EMAIL           VARCHAR2(160) NOT NULL,
    PASSWORD_HASH   VARCHAR2(120) NOT NULL,
    ACTIVO          NUMBER(1)     DEFAULT 1 NOT NULL,
    FECHA_CREACION  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_USUARIOS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_USUARIOS_ACTIVO CHECK (ACTIVO IN (0, 1))
);

CREATE TABLE ROLES (
    ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE       VARCHAR2(40)  NOT NULL,
    DESCRIPCION  VARCHAR2(200),
    CONSTRAINT UK_ROLES_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE USUARIO_ROL (
    USUARIO_ID  NUMBER NOT NULL,
    ROL_ID      NUMBER NOT NULL,
    CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (USUARIO_ID, ROL_ID),
    CONSTRAINT FK_USUARIO_ROL_USUARIO FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIOS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_USUARIO_ROL_ROL FOREIGN KEY (ROL_ID)
        REFERENCES ROLES (ID) ON DELETE CASCADE
);

CREATE TABLE TOKEN_RECUPERACION (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USUARIO_ID  NUMBER        NOT NULL,
    TOKEN       VARCHAR2(64)  NOT NULL,
    EXPIRA_EN   TIMESTAMP     NOT NULL,
    USADO       NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT UK_TOKEN_RECUPERACION UNIQUE (TOKEN),
    CONSTRAINT FK_TOKEN_USUARIO FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIOS (ID) ON DELETE CASCADE,
    CONSTRAINT CK_TOKEN_USADO CHECK (USADO IN (0, 1))
);

CREATE INDEX IX_USUARIO_ROL_ROL ON USUARIO_ROL (ROL_ID);
CREATE INDEX IX_TOKEN_USUARIO ON TOKEN_RECUPERACION (USUARIO_ID);

INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('ADMIN', 'Administracion completa de usuarios y roles');
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('USUARIO', 'Acceso a su propio perfil');
INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES ('AUDITOR', 'Consulta de usuarios y roles');

COMMIT;
